/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppUpdateModal: typeof import('./src/components/update/AppUpdateModal.vue')['default']
    ChartsPreview: typeof import('./src/components/preview/ChartsPreview.vue')['default']
    CheatsheetPreview: typeof import('./src/components/preview/CheatsheetPreview.vue')['default']
    CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
    copy: typeof import('./src/components/SvgIcon copy.vue')['default']
    CreationConfigModal: typeof import('./src/components/CreationConfigModal.vue')['default']
    FlashcardPreview: typeof import('./src/components/preview/FlashcardPreview.vue')['default']
    GlossaryPreview: typeof import('./src/components/preview/GlossaryPreview.vue')['default']
    GraphInfoPanel: typeof import('./src/components/preview/GraphInfoPanel.vue')['default']
    IconPicker: typeof import('./src/components/IconPicker.vue')['default']
    ImportModal: typeof import('./src/components/ImportModal.vue')['default']
    KnowledgeGraphPreview: typeof import('./src/components/preview/KnowledgeGraphPreview.vue')['default']
    LeftPanel: typeof import('./src/components/layout/LeftPanel.vue')['default']
    MainContent: typeof import('./src/components/layout/MainContent.vue')['default']
    MarkdownImagePreview: typeof import('./src/components/MarkdownImagePreview.vue')['default']
    MarkdownView: typeof import('./src/components/MarkdownView.vue')['default']
    MediaDetailModal: typeof import('./src/components/media/MediaDetailModal.vue')['default']
    MediaStatusBadge: typeof import('./src/components/media/MediaStatusBadge.vue')['default']
    MindmapPreview: typeof import('./src/components/preview/MindmapPreview.vue')['default']
    MsMessageBox: typeof import('./src/components/MsMessageBox/MsMessageBox.vue')['default']
    MsMessageContainer: typeof import('./src/components/MsMessage/MsMessageContainer.vue')['default']
    MsModal: typeof import('./src/components/MsModal/MsModal.vue')['default']
    MsTreeItem: typeof import('./src/components/MsTreeItem/MsTreeItem.vue')['default']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    OptionSelector: typeof import('./src/components/OptionSelector.vue')['default']
    QaPreview: typeof import('./src/components/preview/QaPreview.vue')['default']
    QuizPreview: typeof import('./src/components/preview/QuizPreview.vue')['default']
    ResizeHandle: typeof import('./src/components/layout/ResizeHandle.vue')['default']
    RightPanel: typeof import('./src/components/layout/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartupGuideModal: typeof import('./src/components/onboarding/StartupGuideModal.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    'SvgIcon copy': typeof import('./src/components/SvgIcon copy.vue')['default']
    TextEditContextMenu: typeof import('./src/components/TextEditContextMenu.vue')['default']
    TitleBar: typeof import('./src/components/layout/TitleBar.vue')['default']
  }
}
