import test from 'node:test'
import assert from 'node:assert/strict'
import { DatabaseService } from './DatabaseService.js'

const EXPECTED_INSTANCE_METHODS = [
  'backupTo',
  'cancelInterruptedPdfParseRuns',
  'cancelPdfParseRuns',
  'clearFinishedWebImportJobs',
  'close',
  'countMsgs',
  'countPdfSourceLinks',
  'createAgent',
  'createAgentRun',
  'createArtifact',
  'createConv',
  'createConvGroup',
  'createConversationBranch',
  'createDoc',
  'createMcpServer',
  'createMemory',
  'createMsg',
  'createNote',
  'createNoteFolder',
  'createOcrProvider',
  'createOutput',
  'createPdfParseRun',
  'createSkill',
  'createSpace',
  'createSubAgent',
  'createTask',
  'createTokenUsage',
  'createTool',
  'createTrashItem',
  'createWebImportJob',
  'createWiki',
  'createWikiJob',
  'createWikiOcrJob',
  'deleteAgent',
  'deleteAgentRun',
  'deleteArtifact',
  'deleteConv',
  'deleteConvGroup',
  'deleteDoc',
  'deleteMcpServer',
  'deleteMemory',
  'deleteMsg',
  'deleteNote',
  'deleteNoteFolder',
  'deleteOcrProvider',
  'deleteOldTokenUsage',
  'deleteOutput',
  'deletePdfDocument',
  'deletePdfSourceLinks',
  'deleteSkill',
  'deleteSpace',
  'deleteSubAgent',
  'deleteTask',
  'deleteTool',
  'deleteTrashItem',
  'deleteTrashItems',
  'deleteWebImportJob',
  'deleteWiki',
  'deleteWikiSource',
  'emptyTrash',
  'findPdfDocumentByPathHash',
  'getAgent',
  'getAgentRun',
  'getAllSettings',
  'getArtifact',
  'getConv',
  'getMcpServer',
  'getMsg',
  'getNote',
  'getNoteFolder',
  'getOcrProvider',
  'getPdfDocument',
  'getPdfParseRun',
  'getPreviousUserMsg',
  'getSetting',
  'getSpace',
  'getTask',
  'getTokenUsageByAgent',
  'getTokenUsageByModel',
  'getTokenUsageDaily',
  'getTokenUsageSummary',
  'getTrashItem',
  'getWebImportJob',
  'getWiki',
  'getWikiOcrJob',
  'getWikiSource',
  'hasActivePdfSourceLink',
  'importSettings',
  'init',
  'isEnglishNameUnique',
  'listAgentRunsByAgent',
  'listAgentRunsByConversation',
  'listAgents',
  'listArtifactsByGroup',
  'listConvGroups',
  'listConvs',
  'listDocs',
  'listMcpServers',
  'listMemories',
  'listMsgs',
  'listMsgsPaginated',
  'listNoteFolders',
  'listNotes',
  'listOcrProviders',
  'listOutputs',
  'listPdfParseRuns',
  'listPdfSourceLinks',
  'listPdfSourceLinksByTrashId',
  'listPdfSourceLinksForPdf',
  'listPendingWebImportJobs',
  'listSkills',
  'listSpaces',
  'listSubAgents',
  'listTasks',
  'listTasksByGroup',
  'listTokenUsage',
  'listTools',
  'listTrash',
  'listTrashByCategory',
  'listWebImportJobs',
  'listWikiJobs',
  'listWikiOcrJobs',
  'listWikiSources',
  'listWikis',
  'markPdfSourceLinksTrashed',
  'markRunningWebImportJobsInterrupted',
  'relocateToWorkspace',
  'restorePdfSourceLink',
  'setSetting',
  'spaceDocCount',
  'syncBuiltinAgentTemplate',
  'trashItemCount',
  'updateAgent',
  'updateAgentRun',
  'updateArtifact',
  'updateConv',
  'updateConvGroup',
  'updateDoc',
  'updateMcpServer',
  'updateMemory',
  'updateMsg',
  'updateNote',
  'updateNoteFolder',
  'updateOcrProvider',
  'updatePdfDocument',
  'updatePdfParseRun',
  'updatePdfSourceLink',
  'updateSkill',
  'updateSpace',
  'updateSubAgent',
  'updateTask',
  'updateTool',
  'updateWebImportJob',
  'updateWiki',
  'updateWikiOcrJob',
  'updateWikiSource',
  'upsertPdfDocument',
  'upsertPdfSourceLink',
  'upsertWiki',
  'upsertWikiOcrJob',
  'upsertWikiSource',
].sort()

test('DatabaseService keeps its public instance method contract', () => {
  const actual = Object.getOwnPropertyNames(DatabaseService.prototype)
    .filter(name => name !== 'constructor'
      && !name.startsWith('_')
      && typeof Object.getOwnPropertyDescriptor(DatabaseService.prototype, name)?.value === 'function')
    .sort()

  assert.deepEqual(actual, EXPECTED_INSTANCE_METHODS)
  assert.equal(typeof Object.getOwnPropertyDescriptor(DatabaseService.prototype, 'db')?.get, 'function')
})

test('DatabaseService keeps its public static contract', () => {
  assert.equal(typeof DatabaseService.workspaceDbPath, 'function')
  assert.equal(typeof DatabaseService.checkDatabaseIntegrity, 'function')
})
