<script setup>
defineProps({ file: { type: Object, required: true }, fileUrl: { type: String, default: '' }, isDark: Boolean })
const emit = defineEmits(['details'])
</script>
<template>
  <div v-if="file.mediaType === 'image'" class="flex items-center justify-center p-6"><img :src="fileUrl" class="max-w-full rounded-xl shadow-lg" style="max-height:70vh" /></div>
  <div v-else-if="file.remoteMediaReference" class="p-6"><div class="max-w-4xl mx-auto rounded-xl border p-6" :class="isDark ? 'bg-d3 border-bdr' : 'bg-l3 border-bdrF'"><div class="flex items-start gap-4"><div class="w-11 h-11 rounded-xl flex items-center justify-center shrink-0" :class="isDark ? 'bg-violet-400/10 text-violet-300' : 'bg-violet-50 text-violet-600'"><i class="ri-movie-2-line text-[22px]" /></div><div class="min-w-0 flex-1"><div class="text-[14px] font-semibold" :class="isDark ? 'text-wt-main' : 'text-lt-main'">音视频Url引用</div><p class="text-[12px] mt-2 leading-relaxed" :class="isDark ? 'text-wt-dim' : 'text-lt-aux'">此文档只保存安全的 mediaId 引用，不包含原始或签名 URL。解析任务和缓存由媒体模块统一管理。</p><div v-if="file.processingStatus" class="mt-4 flex items-center gap-2 text-[11px]" :class="isDark ? 'text-wt-sub' : 'text-lt-sub'"><i :class="['text-[14px]', ['queued','running'].includes(file.processingStatus.state) ? 'ri-loader-4-line animate-spin' : 'ri-information-line']" /><span>{{ file.processingStatus.label }} · {{ file.processingStatus.detail }}</span></div><button class="mt-5 h-8 px-3 rounded-lg text-[11px] font-medium flex items-center gap-1.5 transition-colors" :class="isDark ? 'bg-brand-400/12 text-brand-300 hover:bg-brand-400/18' : 'bg-brand-50 text-brand-600 hover:bg-brand-100'" @click="emit('details', file)"><i class="ri-file-list-3-line text-[13px]" />查看解析详情</button></div></div></div></div>
  <div v-else-if="file.mediaType === 'audio'" class="flex flex-col items-center gap-4 py-10 px-6"><div class="w-20 h-20 rounded-2xl flex items-center justify-center" :class="isDark ? 'bg-pink-400/8' : 'bg-pink-50'"><i class="ri-music-fill text-[36px]" :class="isDark ? 'text-pink-400' : 'text-pink-500'" /></div><p class="text-[13px] font-medium" :class="isDark ? 'text-wt-main' : 'text-lt-main'">{{ file.name }}</p><audio controls :src="fileUrl" class="w-full max-w-md" /></div>
  <div v-else-if="file.mediaType === 'video'" class="p-6 flex justify-center"><video controls :src="fileUrl" class="w-full max-w-3xl rounded-xl shadow-lg" style="max-height:70vh" /></div>
</template>
