<script setup>
import { computed } from 'vue'
const props = defineProps({ file: { type: Object, required: true }, isDark: Boolean })
const statusLabel = computed(() => ({ text: '可读取', text_with_partial_gaps: '部分页面需要 OCR', mixed_needs_ocr: '混合型，需要 OCR 补齐', scanned_or_image: '扫描件，需要 OCR' })[props.file.pdfStatus?.pdfTextMode] || '已预检')
const recommendation = computed(() => props.file.pdfStatus?.recommendation?.reason || props.file.pdfStatus?.recommendation?.action || '')
</script>
<template>
  <div class="p-6"><div class="max-w-4xl mx-auto rounded-xl border p-5" :class="isDark ? 'bg-d3 border-bdr' : 'bg-l3 border-bdrF'"><div class="flex items-start justify-between gap-4"><div><div class="text-[13px] font-semibold" :class="isDark ? 'text-wt-main' : 'text-lt-main'">{{ statusLabel }}</div><div class="text-[11px] mt-1" :class="isDark ? 'text-wt-dim' : 'text-lt-aux'">{{ file.pdfStatus.pageCount || 0 }} 页 · 文本覆盖率 {{ Math.round((file.pdfStatus.textCoverageRatio || 0) * 100) }}%</div></div><span class="ctx-pill shrink-0" :class="isDark ? 'bg-red-400/8 text-red-400 border border-red-400/20' : 'bg-red-50 text-red-500 border border-red-100'">PDF</span></div><div v-if="recommendation" class="mt-4 text-[14px] leading-relaxed" :class="isDark ? 'text-wt-sub' : 'text-lt-sub'">{{ recommendation }}</div><div class="mt-4 grid grid-cols-3 gap-2"><div v-for="metric in [{l:'候选 OCR 页',v:file.pdfStatus.ocrCandidateCount||0},{l:'已扫描页',v:file.pdfStatus.scannedPages||0},{l:'缓存',v:file.pdfStatus.cacheHit?'命中':'已更新'}]" :key="metric.l" class="rounded-lg px-3 py-2" :class="isDark ? 'bg-d4/50' : 'bg-l4/60'"><div class="text-[10px]" :class="isDark ? 'text-wt-dim' : 'text-lt-aux'">{{ metric.l }}</div><div class="text-[13px] font-semibold mt-0.5" :class="isDark ? 'text-wt-main' : 'text-lt-main'">{{ metric.v }}</div></div></div><div v-if="file.pdfStatus.content" class="mt-5"><div class="text-[11px] mb-2" :class="isDark ? 'text-wt-dim' : 'text-lt-aux'">文本预览</div><pre class="text-[12px] leading-relaxed whitespace-pre-wrap max-h-[360px] overflow-auto rounded-lg p-3" :class="isDark ? 'bg-d4 text-wt-sub' : 'bg-l4 text-lt-sub'">{{ file.pdfStatus.content }}</pre></div></div></div>
</template>
<style scoped>.ctx-pill{font-size:11px;border-radius:6px;padding:3px 8px;display:inline-flex;align-items:center;gap:4px}</style>
