import { tool } from 'langchain'
import { z } from 'zod'
import { OfficeCliToolService } from './OfficeCliToolService.js'

const officeActionSchema = z.object({
  command: z.enum([
    'add',
    'clone',
    'set',
    'remove',
    'get',
    'query',
    'raw_set',
    'raw-set',
    'replace_text',
    'add_paragraph',
    'add_heading',
    'add_table',
    'add_picture',
    'add_comment',
    'add_field',
    'add_header',
    'add_footer',
    'set_header_footer',
    'add_form_control',
    'add_slide',
    'add_shape',
    'add_textbox',
    'add_chart',
    'add_speaker_notes',
    'add_connector',
    'add_sheet',
    'set_cell',
    'set_formula',
    'set_range',
    'define_name',
  ]).describe('Office action 类型。通用命令：add/clone/set/remove/get/query/raw_set/replace_text；快捷动作覆盖 docx/pptx/xlsx 常用创建编辑。'),
  path: z.string().optional().describe('OfficeCLI DOM 路径或单元格路径，例如 /body、/slide[1]、/Sheet1/A1。'),
  part: z.string().optional().describe('raw_set 的目标 part，例如 /document、/settings、/workbook、/word/header1.xml。'),
  xpath: z.string().optional().describe('raw_set 的 XPath。'),
  rawAction: z.enum(['append', 'prepend', 'insertbefore', 'insertafter', 'replace', 'remove', 'setattr']).optional().describe('raw_set 的动作。'),
  xml: z.string().optional().describe('raw_set 的 XML 片段或 setattr 的 key=value。'),
  selector: z.string().optional().describe('query 操作的 CSS-like selector，或 set/remove 的选择器路径。'),
  type: z.string().optional().describe('add 操作的 Office 元素类型，例如 paragraph、slide、shape、table、chart。'),
  elementType: z.string().optional().describe('add 操作的 Office 元素类型；与 type 等价，优先用于避免和 action 类型混淆。'),
  props: z.record(z.string(), z.any()).optional().describe('传给 officecli --prop 的属性对象，例如 { "text": "标题", "style": "Heading1" }。数组/对象会 JSON 序列化。'),
  after: z.string().optional().describe('add/clone 插入到该路径之后。after/before/index 三选一。'),
  before: z.string().optional().describe('add/clone 插入到该路径之前。after/before/index 三选一。'),
  index: z.number().optional().describe('add/clone 的插入位置，0-based。after/before/index 三选一。'),
  from: z.string().optional().describe('clone 动作或 add --from 的来源元素路径。'),
  depth: z.number().optional().describe('get 动作展开深度，0-20。'),
  find: z.string().optional().describe('replace_text 或 set 的查找文本。'),
  replace: z.string().optional().describe('replace_text 或 set 的替换文本。'),
  text: z.string().optional().describe('add_paragraph/add_heading 的文本快捷字段。'),
  level: z.number().optional().describe('add_heading 的标题级别 1-6。'),
  value: z.union([z.string(), z.number(), z.boolean()]).optional().describe('set_cell/set_range 的值快捷字段。'),
  values: z.any().optional().describe('set_range 的二维数组或结构化值，会作为 JSON prop 传给 OfficeCLI。'),
  formula: z.string().optional().describe('set_cell/set_formula 的公式快捷字段。'),
  src: z.string().optional().describe('add_picture 的图片路径。'),
  range: z.string().optional().describe('Excel range 或图表/表格数据区域。'),
  cell: z.string().optional().describe('Excel cell 路径，例如 /Sheet1/A1。'),
  name: z.string().optional().describe('工作表、形状、命名范围等名称。'),
  title: z.string().optional().describe('幻灯片、图表等标题。'),
  chartType: z.string().optional().describe('图表类型，例如 column、line、bar、pie。'),
  confirm: z.boolean().optional().describe('remove/raw_set 操作必须显式传 true。'),
})

export function createOfficeWriteTool(workDirService, allowedOperations = [], options = {}) {
  const service = new OfficeCliToolService(workDirService, options)
  const allowed = [...new Set(allowedOperations)]
  return tool(
    async (input) => service.invoke(input, allowed),
    {
      name: 'office_write',
      description: [
        'OfficeCLI 写入路由工具，用于创建和编辑 .docx、.pptx、.xlsx。',
        `当前允许的 operation：${allowed.join(', ') || '无'}`,
        '创建/编辑必须使用结构化 actions，不开放 raw command、watch 或任意 shell。',
        '通用 actions 支持 add/clone/set/remove/get/query/raw_set/replace_text；快捷 actions 覆盖 Word 段落表格图片批注字段表单、PPT 幻灯片形状图片图表备注连接器、Excel 工作表单元格区域公式表格图表命名范围。',
        'Agent 可按需自行决定 useBatch=true 或 allowRawXml=true。useBatch 会把 actions 自动编译为 OfficeCLI batch JSON 后一次执行，适合大量稳定动作；raw_set 需要 allowRawXml=true 且 action.confirm=true。',
        '使用 batch 或 raw_set 时，工具会强制执行后置 issues/validate 检查，即使 runChecks=false 也不会跳过。',
        '编辑现有 Office 文件时默认输出副本，不覆盖源文件；输出写入 /agents/{agent}/outputs/YYYY-MM-DD/。',
        '不确定元素类型或属性名时，先调用 operation=help 查询 OfficeCLI schema，再执行 create/edit。',
      ].join('\n'),
      schema: z.object({
        operation: z.enum(['help', 'create', 'edit']).describe('要执行的 Office 子操作。help 查询 OfficeCLI schema；create 创建新文件；edit 编辑现有文件副本。'),
        path: z.string().optional().describe('edit 操作的输入 Office 文件路径，必须在授权工作区内。create/help 不需要。'),
        filename: z.string().optional().describe('输出文件名，不接受目录。create 可用 report.docx；edit 可用 edited-report.docx。未传时自动生成。'),
        format: z.enum(['docx', 'pptx', 'xlsx']).optional().describe('create/help 的目标格式。create 可从 filename 扩展名推断。'),
        element: z.string().optional().describe('help 操作的元素类型，例如 paragraph、shape、cell、chart。'),
        verb: z.string().optional().describe('help 操作的动词过滤，例如 add、set、get、query、remove。'),
        json: z.boolean().optional().describe('help 是否请求 JSON schema，默认 true。'),
        actions: z.array(officeActionSchema).optional().describe('create/edit 要执行的结构化动作，最多 100 个。'),
        useBatch: z.boolean().optional().describe('是否使用 officecli batch 一次性执行 actions。默认 false；大量稳定动作可设为 true 节省时间。'),
        allowRawXml: z.boolean().optional().describe('是否允许 raw_set。默认 false；使用 raw_set 时每个 action 仍必须 confirm=true。'),
        runChecks: z.boolean().optional().describe('create/edit 后是否运行 view issues 和 validate 轻量检查，默认 true。useBatch 或 allowRawXml 为 true 时会强制检查。'),
      }),
    },
  )
}
