export const PPTX_STYLE_OPTIONS = [
  { value: 'auto', label: '自动选择', description: '根据场景自动选择 PPT Master 风格。', category: 'smart' },
  { value: 'free', label: '自由设计', description: '不绑定具体模板，使用 PPT Master 项目结构、SVG 规范和 PPTX 导出链路。', category: 'free' },
  { value: 'deck:中国电信', label: '政企数字化方案汇报', description: '红色稳重政企风，适合数字化转型方案、运营商能力介绍、内部战略汇报。', category: '完整模板 / 政企方案' },
  { value: 'deck:中国电建_常规', label: '工程项目稳重蓝版', description: '工程蓝商务风，适合工程项目进展、技术方案、年度总结和商务沟通。', category: '完整模板 / 工程汇报' },
  { value: 'deck:中国电建_现代', label: '大型工程现代蓝版', description: '现代蓝色工程展示风，适合重大工程、海外市场、技术成果和项目发布。', category: '完整模板 / 工程发布' },
  { value: 'deck:中汽研_商务', label: '汽车评测高端商务版', description: '深蓝高端商务风，适合汽车评测、认证服务、技术推广和客户来访。', category: '完整模板 / 汽车商务' },
  { value: 'deck:中汽研_常规', label: '汽车技术认证常规版', description: '清晰蓝色技术汇报风，适合产品认证、检测服务、技术说明和常规商务介绍。', category: '完整模板 / 汽车技术' },
  { value: 'deck:中汽研_现代', label: '汽车科技发布深色版', description: '深色科技发布风，适合智能汽车、前沿技术、战略发布和高端技术展示。', category: '完整模板 / 汽车科技' },
  { value: 'deck:招商银行', label: '金融产品与交易银行方案', description: '红白金融产品风，适合交易银行、销售收款方案、客户案例和分行培训。', category: '完整模板 / 金融方案' },
  { value: 'deck:重庆大学', label: '高校学术答辩蓝版', description: '高校蓝学术风，适合论文答辩、研究报告、教学演示和学术交流。', category: '完整模板 / 学术汇报' },
  { value: 'layout:academic_defense', label: '学术答辩结构', description: '适合论文答辩、课题汇报、基金申请和研究进展，结构完整、信息层级清楚。', category: '结构模板 / 学术' },
  { value: 'layout:ai_ops', label: 'AI 运维架构汇报', description: '适合 AI 运维、IT 架构、通信基础设施和数字化转型，偏系统图和流程表达。', category: '结构模板 / 技术架构' },
  { value: 'layout:government_blue', label: '政务蓝管理汇报', description: '适合管理层汇报、工作总结、五年规划、招商方案和政策解读，稳重克制。', category: '结构模板 / 管理汇报' },
  { value: 'layout:government_red', label: '政务红重点汇报', description: '适合重点工作、政策宣讲、项目介绍和政务总结，强调正式感和重点推进。', category: '结构模板 / 政务汇报' },
  { value: 'layout:medical_university', label: '医学学术汇报', description: '适合医学科研、病例讨论、医院工作报告和医学培训，专业、干净、低干扰。', category: '结构模板 / 医学' },
  { value: 'layout:pixel_retro', label: '像素复古技术分享', description: '适合技术分享、编程教程、工程复盘和极客主题演示，暗色、复古、识别度高。', category: '结构模板 / 技术分享' },
  { value: 'layout:psychology_attachment', label: '心理咨询培训汇报', description: '适合心理治疗培训、依恋理论、咨询案例分析和专业讲座，柔和、亲和、专业。', category: '结构模板 / 心理培训' },
  { value: 'brand:anthropic', label: 'AI 技术橙色品牌风', description: '温和橙色 AI 品牌风，适合大模型、Agent、开发者分享和产品发布。', category: '品牌风格 / AI 技术' },
  { value: 'brand:google', label: '多色清爽科技品牌风', description: 'Google 式多色清爽风，适合科技产品、开发者活动、教育培训和生态介绍。', category: '品牌风格 / 科技产品' },
]

export const HTML_STYLE_OPTIONS = [
  { value: 'auto', label: '自动选择', description: '根据场景自动选择 html-ppt-skill theme 或 full-deck。', category: 'smart' },
  { value: 'theme:minimal-white', label: 'minimal-white', description: 'Light & calm theme', category: 'Light & calm' },
  { value: 'theme:editorial-serif', label: 'editorial-serif', description: 'Light & calm theme', category: 'Light & calm' },
  { value: 'theme:soft-pastel', label: 'soft-pastel', description: 'Light & calm theme', category: 'Light & calm' },
  { value: 'theme:xiaohongshu-white', label: 'xiaohongshu-white', description: 'Light & calm theme', category: 'Light & calm' },
  { value: 'theme:solarized-light', label: 'solarized-light', description: 'Light & calm theme', category: 'Light & calm' },
  { value: 'theme:catppuccin-latte', label: 'catppuccin-latte', description: 'Light & calm theme', category: 'Light & calm' },
  { value: 'theme:sharp-mono', label: 'sharp-mono', description: 'Bold & statement theme', category: 'Bold & statement' },
  { value: 'theme:neo-brutalism', label: 'neo-brutalism', description: 'Bold & statement theme', category: 'Bold & statement' },
  { value: 'theme:bauhaus', label: 'bauhaus', description: 'Bold & statement theme', category: 'Bold & statement' },
  { value: 'theme:swiss-grid', label: 'swiss-grid', description: 'Bold & statement theme', category: 'Bold & statement' },
  { value: 'theme:memphis-pop', label: 'memphis-pop', description: 'Bold & statement theme', category: 'Bold & statement' },
  { value: 'theme:catppuccin-mocha', label: 'catppuccin-mocha', description: 'Cool & dark theme', category: 'Cool & dark' },
  { value: 'theme:dracula', label: 'dracula', description: 'Cool & dark theme', category: 'Cool & dark' },
  { value: 'theme:tokyo-night', label: 'tokyo-night', description: 'Cool & dark theme', category: 'Cool & dark' },
  { value: 'theme:nord', label: 'nord', description: 'Cool & dark theme', category: 'Cool & dark' },
  { value: 'theme:gruvbox-dark', label: 'gruvbox-dark', description: 'Cool & dark theme', category: 'Cool & dark' },
  { value: 'theme:rose-pine', label: 'rose-pine', description: 'Cool & dark theme', category: 'Cool & dark' },
  { value: 'theme:arctic-cool', label: 'arctic-cool', description: 'Cool & dark theme', category: 'Cool & dark' },
  { value: 'theme:sunset-warm', label: 'sunset-warm', description: 'Warm & vibrant theme', category: 'Warm & vibrant' },
  { value: 'theme:glassmorphism', label: 'glassmorphism', description: 'Effect-heavy theme', category: 'Effect-heavy' },
  { value: 'theme:aurora', label: 'aurora', description: 'Effect-heavy theme', category: 'Effect-heavy' },
  { value: 'theme:rainbow-gradient', label: 'rainbow-gradient', description: 'Effect-heavy theme', category: 'Effect-heavy' },
  { value: 'theme:blueprint', label: 'blueprint', description: 'Effect-heavy theme', category: 'Effect-heavy' },
  { value: 'theme:terminal-green', label: 'terminal-green', description: 'Effect-heavy theme', category: 'Effect-heavy' },
  { value: 'theme:corporate-clean', label: 'corporate-clean', description: 'Light & professional theme', category: 'Light & professional' },
  { value: 'theme:pitch-deck-vc', label: 'pitch-deck-vc', description: 'Light & professional theme', category: 'Light & professional' },
  { value: 'theme:academic-paper', label: 'academic-paper', description: 'Light & professional theme', category: 'Light & professional' },
  { value: 'theme:japanese-minimal', label: 'japanese-minimal', description: 'Light & professional theme', category: 'Light & professional' },
  { value: 'theme:engineering-whiteprint', label: 'engineering-whiteprint', description: 'Light & professional theme', category: 'Light & professional' },
  { value: 'theme:magazine-bold', label: 'magazine-bold', description: 'Bold & editorial theme', category: 'Bold & editorial' },
  { value: 'theme:news-broadcast', label: 'news-broadcast', description: 'Bold & editorial theme', category: 'Bold & editorial' },
  { value: 'theme:midcentury', label: 'midcentury', description: 'Bold & editorial theme', category: 'Bold & editorial' },
  { value: 'theme:retro-tv', label: 'retro-tv', description: 'Bold & editorial theme', category: 'Bold & editorial' },
  { value: 'theme:cyberpunk-neon', label: 'cyberpunk-neon', description: 'Effect-heavy / dramatic theme', category: 'Effect-heavy / dramatic' },
  { value: 'theme:vaporwave', label: 'vaporwave', description: 'Effect-heavy / dramatic theme', category: 'Effect-heavy / dramatic' },
  { value: 'theme:y2k-chrome', label: 'y2k-chrome', description: 'Effect-heavy / dramatic theme', category: 'Effect-heavy / dramatic' },
  { value: 'deck:xhs-white-editorial', label: 'xhs-white-editorial', description: '白底杂志风，小红书图文、中文重内容表达', category: 'full-deck' },
  { value: 'deck:graphify-dark-graph', label: 'graphify-dark-graph', description: '暗底知识图谱，AI 原生、数据可视化、开发工具发布', category: 'full-deck' },
  { value: 'deck:knowledge-arch-blueprint', label: 'knowledge-arch-blueprint', description: '奶油蓝图架构，系统架构、工程白皮书、数据流', category: 'full-deck' },
  { value: 'deck:hermes-cyber-terminal', label: 'hermes-cyber-terminal', description: '暗终端技术评审，CLI、Agent、开发工具复盘', category: 'full-deck' },
  { value: 'deck:obsidian-claude-gradient', label: 'obsidian-claude-gradient', description: 'GitHub 暗紫渐变，开发者工作流、MCP、Agent 教程', category: 'full-deck' },
  { value: 'deck:testing-safety-alert', label: 'testing-safety-alert', description: '红琥珀警示，安全、风险、事故复盘、红队评审', category: 'full-deck' },
  { value: 'deck:xhs-pastel-card', label: 'xhs-pastel-card', description: '柔和马卡龙卡片，生活方式、个人成长、轻内容', category: 'full-deck' },
  { value: 'deck:dir-key-nav-minimal', label: 'dir-key-nav-minimal', description: '方向键极简 keynote，一个观点一页的公开演讲', category: 'full-deck' },
  { value: 'deck:pitch-deck', label: 'pitch-deck', description: '白底蓝紫 VC 风，融资路演、创业项目', category: 'full-deck' },
  { value: 'deck:product-launch', label: 'product-launch', description: '暗封面 + 浅内容，产品发布、发布会', category: 'full-deck' },
  { value: 'deck:tech-sharing', label: 'tech-sharing', description: 'GitHub dark + 终端代码块，技术分享', category: 'full-deck' },
  { value: 'deck:weekly-report', label: 'weekly-report', description: '商务清晰周报，KPI、进展、下周计划', category: 'full-deck' },
  { value: 'deck:xhs-post', label: 'xhs-post', description: '3:4 小红书图文 / Instagram carousel', category: 'full-deck' },
  { value: 'deck:course-module', label: 'course-module', description: '温暖纸张教学模块，课程、工作坊', category: 'full-deck' },
  { value: 'deck:presenter-mode-reveal', label: 'presenter-mode-reveal', description: '演讲者模式专用，技术分享、课程、路演逐字稿', category: 'full-deck' },
]
