import { createRouter, createWebHashHistory } from 'vue-router'

const router = createRouter({
  history: createWebHashHistory(),
  routes: [
    {
      path: '/landing',
      name: 'Landing',
      component: () => import('@/views/landing/index.vue'),
      meta: { noLayout: true, title: 'Reviva - 智能学习工作台' },
    },
    {
      path: '/login',
      name: 'Login',
      component: () => import('@/views/login/index.vue'),
      meta: { noLayout: true, layout: { iconRail: false } },
    },
    {
      path: '/',
      name: 'Dashboard',
      component: () => import('@/views/dashboard/index.vue'),
      meta: { title: 'Dashboard', icon: 'ri-dashboard-3-line', layout: { iconRail: true, iconRailWidth: 52 } },
    },
    {
      path: '/workchat',
      name: 'Learn',
      component: () => import('@/views/workchat/index.vue'),
      meta: { title: '学习台', icon: 'ri-chat-smile-2-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/spaces',
      name: 'Spaces',
      component: () => import('@/views/spaces/index.vue'),
      meta: { title: '知识库', icon: 'ri-database-2-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/spaces/:id',
      name: 'SpaceDetail',
      component: () => import('@/views/spaces/detail.vue'),
      meta: { title: '知识库详情', icon: 'ri-database-2-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/docs-manage',
      name: 'DocsManage',
      component: () => import('@/views/docs/index.vue'),
      meta: { title: '文档管理', icon: 'ri-folder-2-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/notes',
      name: 'Notes',
      component: () => import('@/views/notes/index.vue'),
      meta: { title: '笔记', icon: 'ri-note-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/wiki',
      name: 'Wiki',
      component: () => import('@/views/wiki/index.vue'),
      meta: { title: 'Wiki', icon: 'ri-book-3-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/recycle-bin',
      name: 'RecycleBin',
      component: () => import('@/views/recycle-bin/index.vue'),
      meta: { title: '回收站', icon: 'ri-delete-bin-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/workspace',
      name: 'Workspace',
      component: () => import('@/views/workspace/index.vue'),
      meta: { title: '对话工作台', icon: 'ri-chat-3-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/agents',
      name: 'Agents',
      component: () => import('@/views/agents/index.vue'),
      meta: { title: '智能体', icon: 'ri-sparkling-2-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/agents/create',
      name: 'AgentCreate',
      component: () => import('@/views/agents/edit.vue'),
      meta: { title: '创建 Agent', icon: 'ri-sparkling-2-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/agents/:id/edit',
      name: 'AgentEdit',
      component: () => import('@/views/agents/edit.vue'),
      meta: { title: '编辑 Agent', icon: 'ri-sparkling-2-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/skills',
      name: 'Skills',
      component: () => import('@/views/skills/index.vue'),
      meta: { title: 'Skills', icon: 'ri-flashlight-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/tools',
      name: 'Tools',
      component: () => import('@/views/tools/index.vue'),
      meta: { title: '工具', icon: 'ri-tools-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/tasks',
      name: 'Tasks',
      component: () => import('@/views/tasks/index.vue'),
      meta: { title: '任务', icon: 'ri-list-check-3', layout: { iconRail: true, iconRailWidth: 52 } },
    },
    {
      path: '/translate',
      name: 'Translate',
      component: () => import('@/views/translate/index.vue'),
      meta: { title: '翻译', icon: 'ri-translate-2', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/outputs',
      name: 'Outputs',
      component: () => import('@/views/outputs/index.vue'),
      meta: { title: '输出中心', icon: 'ri-file-chart-line', layout: { iconRail: true, iconRailWidth: 52 } },
    },
    {
      path: '/profile',
      name: 'Profile',
      component: () => import('@/views/profile/index.vue'),
      meta: { title: '个人中心', icon: 'ri-user-3-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/profile/transactions',
      name: 'ProfileTransactions',
      component: () => import('@/views/profile/transactions.vue'),
      meta: { title: '积分流水', icon: 'ri-file-list-3-line', layout: { iconRail: true, iconRailWidth: 48 } },
    },
    {
      path: '/settings',
      name: 'Settings',
      component: () => import('@/views/settings/index.vue'),
      meta: { title: '设置', icon: 'ri-settings-3-line', layout: { iconRail: true, iconRailWidth: 48 } },
      redirect: '/settings/default-models',
      children: [
        {
          path: 'account',
          name: 'SettingsAccount',
          component: () => import('@/views/settings/sections/AccountSection.vue'),
          meta: { title: '账号与连接' },
        },
        {
          path: 'default-models',
          name: 'SettingsDefaultModels',
          component: () => import('@/views/settings/sections/DefaultModelsSection.vue'),
          meta: { title: '默认模型' },
        },
        {
          path: 'models',
          name: 'SettingsModels',
          component: () => import('@/views/settings/sections/ModelsSection.vue'),
          meta: { title: '模型服务' },
        },
        {
          path: 'directory',
          name: 'SettingsDirectory',
          component: () => import('@/views/settings/sections/DirectorySection.vue'),
          meta: { title: '目录与权限' },
        },
        {
          path: 'environment',
          name: 'SettingsEnvironment',
          component: () => import('@/views/settings/sections/EnvironmentSection.vue'),
          meta: { title: '环境管理' },
        },
        {
          path: 'ocr',
          name: 'SettingsOcr',
          component: () => import('@/views/settings/sections/OcrSection.vue'),
          meta: { title: 'OCR 服务' },
        },
        {
          path: 'network',
          name: 'SettingsNetwork',
          component: () => import('@/views/settings/sections/NetworkSection.vue'),
          meta: { title: '网络与代理' },
        },
        {
          path: 'sandbox',
          name: 'SettingsSandbox',
          component: () => import('@/views/settings/sections/SandboxSection.vue'),
          meta: { title: '沙箱与限流' },
        },
        {
          path: 'memory',
          name: 'SettingsMemory',
          component: () => import('@/views/settings/sections/MemorySection.vue'),
          meta: { title: '记忆管理' },
        },
        {
          path: 'usage',
          name: 'SettingsUsage',
          component: () => import('@/views/settings/sections/UsageSection.vue'),
          meta: { title: '用量统计' },
        },
        {
          path: 'preference',
          name: 'SettingsPreference',
          component: () => import('@/views/settings/sections/PreferenceSection.vue'),
          meta: { title: '偏好配置' },
        },
        {
          path: 'shortcuts',
          name: 'SettingsShortcuts',
          component: () => import('@/views/settings/sections/ShortcutsSection.vue'),
          meta: { title: '快捷键' },
        },
        {
          path: 'notifications',
          name: 'SettingsNotifications',
          component: () => import('@/views/settings/sections/NotificationsSection.vue'),
          meta: { title: '通知与启动' },
        },
        {
          path: 'data',
          name: 'SettingsData',
          component: () => import('@/views/settings/sections/DataSection.vue'),
          meta: { title: '数据与备份' },
        },
        {
          path: 'about',
          name: 'SettingsAbout',
          component: () => import('@/views/settings/sections/AboutSection.vue'),
          meta: { title: '系统版本' },
        },
        {
          path: 'author',
          name: 'SettingsAuthor',
          component: () => import('@/views/settings/sections/AuthorSection.vue'),
          meta: { title: '关于作者' },
        },
      ],
    },
    // {
    //   path: '/legal/user-agreement',
    //   name: 'UserAgreement',
    //   component: () => import('@/views/legal/UserAgreement.vue'),
    //   meta: { title: '用户协议', icon: 'ri-file-list-3-line', layout: { iconRail: true, iconRailWidth: 48 } },
    // },
    // {
    //   path: '/legal/privacy-policy',
    //   name: 'PrivacyPolicy',
    //   component: () => import('@/views/legal/PrivacyPolicy.vue'),
    //   meta: { title: '隐私政策', icon: 'ri-lock-line', layout: { iconRail: true, iconRailWidth: 48 } },
    // },
    // {
    //   path: '/test',
    //   name: 'Test',
    //   component: () => import('@/views/test/index.vue'),
    //   meta: { title: '组件测试', icon: 'ri-test-tube-line', layout: { iconRail: true, iconRailWidth: 52 } },
    // },
  ],
})

export default router
