export const DEEPAGENTS_EXECUTION_TOOL_NAME = 'execute'
export const HIDDEN_COMMAND_COMPATIBILITY_TOOL_NAMES = ['bash', 'command', 'shell']
export const DEEPAGENTS_EXECUTION_TOOL_EXCLUSION = [
  DEEPAGENTS_EXECUTION_TOOL_NAME,
  ...HIDDEN_COMMAND_COMPATIBILITY_TOOL_NAMES,
]

export const UNLIMITED_RECURSION_LIMIT = 10000
